language: ruby

rvm:
  - 2.1
  - 2.2.0
  - rbx-2

gemfile:
 - Gemfile

branches:
  only:
    - master
    - fix-dependencies

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: rbx-2
